#!/bin/bash

name=$1
path=$2

if [ -z $name ]; then
  echo "Session needs a name"
  exit 1
fi

if [ -z $path ]; then
  $path = "."
fi

tmux new-session -s $1 -c $2 -d
tmux rename-window -t 0 code
tmux new-window -n "build + git"
tmux attach-session -t $1
